### ISSUE TITLE
more combat VP markers to account for worm doubling rewards

### ISSUE THREAD

**Issue by dotdotdot-tts** [rogeriocamorim/duneBugSuggestionTracker#16]
in the previous mod, there were enough combat VP markers for economic supremacy to account for all possible VPs for the combat.

since worms can double rewards, there should be enough combat VP markers to account for that.
- spice freighters - 2 combat VP markers
- battle for arakeen - 3 combat VP markers
- battle for imperial basin - 4 combat VP markers
- battle for spice refinery - 4 combat VP markers

currently:
![combat vp](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/154347378/4a2d6201-2d49-48b7-972f-d094787fe63b)

**Comment by Chatanga** [comment]
Fixed in [Cleaned unused content + fixed VP cardinalities.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/8dc552f020331ae4163801839b86b55e2ed4dfdd).

Slightly adjusted the semantics of the symbol: 1 “sun” for a VP and 2 “suns” for a x2 VP. The formers should be above the latters. It's just cosmetic and doesn't change anything (a VP is a VP).

**Comment by rogeriocamorim** [comment]
In the mod
