### ISSUE TITLE
Adding Paul's home brew

### ISSUE THREAD

**Issue by joeklein9** [rogeriocamorim/duneBugSuggestionTracker#21]
If at all possible, would be wonderful to have the option to choose a different deck at set up that includes the cards listed in Paul's home brew here: https://boardgamegeek.com/thread/3213458/merakons-house-blend

I think it would just involve adding the new cards and new intrigues. No need to mess with leader selection. 

Thank you!

**Comment by rogeriocamorim** [comment]
Just to let some msg here that this **may** be done in the future. But there are no plans for now.

**Comment by scmccarthy** [comment]
Ability to select from custom decks would be huge for long-term enjoyment. Even better than flat-out adding support for the expansions.

**Comment by scmccarthy** [comment]
Just wanted to mention explicitly that another part of this is allowing players to use leaders from Base/Ix without adding all (or even any) of the other components from Base/Ix.

**Comment by J00lsy** [comment]
I’d like to second Joe's request. It would be absolutely awesome to play the designer's custom set which he considers the best way to play.

**Comment by supertopi** [comment]
👍  this would be an awesome addition to the mod

**Comment by rogeriocamorim** [comment]
If you really wanna test that there is a way. 
Just a comment that any problem/bug do not report here since that is not a optinonal.

1- Open the mod.
2- Click on Modding -> Scripting.
It will take a time to load a window
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/1370987/89bb3fbe-abe0-4c7d-b86e-8b9c2776ccbf)

Press CTRL + A to select all ( it will not show that is selected but it is) and press CTRL + c to copy.

Open a notepad / Notepad++ etc... and past the code.

You can look for those..
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/1370987/4f6d4aab-3aa2-4ad1-9b24-805b96f84c7f)

Those are the list of cards in game and their max quantity.

Set as you like. Copy the hole code and past on the TTS Script screen.
Press Save & Play it will reload the mod with your cards changes.

PS.: Do not add more cards of certain type. It can cause the mod the bug.

**Comment by rogeriocamorim** [comment]
Added on the last mod release.
![image](https://github.com/user-attachments/assets/0ea21917-a32d-449f-a0c9-cd36eb7c9270)
