### ISSUE TITLE
Error which breaks turns when loading a save

### ISSUE THREAD

**Issue by Tarpsukka** [rogeriocamorim/duneBugSuggestionTracker#33]
Error in Script (Global): chunk_3:(3288,13-36): Wrong player color!

Not sure how to reproduce this.

**Comment by Chatanga** [comment]
This is actually not a bug. The mod simply expects you to choose a valid color before loading the save, otherwise you will get this error. To be honest, this is a residual requirement that serves no purpose today. I will probably remove it with the next fix on the turn system. In the meantime, simply choose a color after creating your game, but before loading your save (or otherwise load it again).

**Comment by Chatanga** [comment]
[Fixed issues:](https://github.com/aaittouares/Dune_Uprising_TTS/commit/1bbac1e5027e986b2cc15d300448f15a690f72e1)
- Error which breaks turns when loading a save.
- Hotseat not changing color for active player.
Enhancements:
- Alternate "Take Place" / "End Turn" button in hotseat.
- Smart player switch in hotseat with 2 players (in 4P and 6P modes).
