### ISSUE TITLE
Player gets a message like "Player has no leader selected" midway through game and can't progress.

### ISSUE THREAD

**Issue by maznaz-ha** [rogeriocamorim/duneBugSuggestionTracker#42]
Unfortunately I have no further specifics as the party quit without providing them, but the game beam unplayable. It was a 4 player and the leader was reverend mother Jessica. They became unable to click any board spaces or faction bump etc as that message was given to them each time. I did notice that their player board had become unlocked somehow. This was all after a rewind when we had been given two contracts instead of one (possibly due to lag). A further rewind could not make the game playable however and the green player was unable to continue

**Comment by aaittouares** [comment]
unfortunately, cannot do very much about  this issue since there is no specific details about what really happened or what possible human error broke the game (you can do a lot of things in TTS that we cannot control and can break stuff)

When you have such cases, please make a save of the game so you can provide it to us and we can further analyse it.

If you happen to stumble upon this, provide a save and we'll look further into it.

**Comment by Chatanga** [comment]
[Fixed broken game when reloading after Jessica became Reverend Mother.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/62cde3d2e5ee7c4ad7190d82df621c10ec1efc3d)

**Comment by aaittouares** [comment]
Fixed and deployed
