### ISSUE TITLE
Sardaukar contract duplicity

### ISSUE THREAD

**Issue by rogeriocamorim** [rogeriocamorim/duneBugSuggestionTracker#54]
When a player select Shaddam Corrino there are Sardaukar contract on the contract bag and over the leader.

So we need to remove from the bag.

**Comment by Chatanga** [comment]
But we remove from the bag, which is why it actually works 99.99% of the time. The remaining 0.01% is the strange case you observed. Looking at the code, I can imagine a race condition where a sardaukar contract taken from the bag is redirected to replenish another sardaukar contract taken from the selected pair, but that is not the same situation. More background information is definitely needed here.

**Comment by rogeriocamorim** [comment]
I can check again running some games to see if was some weird situation. 
But the 4 player selected the emperor and had the contracts on him. But after buying some contracts the Sadukar show up and checking the bag there were another there also.

**Comment by Chatanga** [comment]
Of course it was an exceptional situation. Everyone plays with the CHOAM module and no one has encountered such a "bug" yet. And I wrote "bug", because if a player selected Shaddam, collected his 2 contracts on his leader card and finally found 2 other Sardaukar contracts later in the bag, there is clearly something quite broken elsewhere. I'm starting to suspect that some people have done unholy things with the save...

**Comment by rogeriocamorim** [comment]
Will close since it did not repeated anymore.
